#!/usr/bin/env false zsh
# -*- coding: utf-8 -*-
	# shellcheck shell=bash
	# shellcheck source=/dev/null
	# shellcheck disable=2128

# ?########################################## parameter expansion tips
	#? ${PATH//:/\\n}    - replace all colons with newlines
	#? ${PATH// /}       - strip all spaces
	#? ${VAR##*/}        - return only final element in path (program name)
	#? ${VAR%/*}         - return only path (without program name)

#? ######################## MANPATH
    declare -x MANPATH=" \
        /usr/local/opt/coreutils/libexec/gnuman:\
        /usr/share/man:\
        /usr/local/share/man:\
        /usr/local/opt/erlang/lib/erlang/man:\
        /Library/Frameworks/Python.framework/Versions/3.8/share/man/man1:\
        /usr/local/texlive/2020/texmf-dist/doc/man:\
        "
    MANPATH="${MANPATH// /}"

    export INFOPATH="/usr/local/texlive/2020/texmf-dist/doc/info:$INFOPATH"

#? ######################## PATH
    # /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/bin/:\

    declare -x PATH="\
        /usr/local/Cellar/gnupg/2.2.21/bin/:\
        /usr/local/opt/coreutils/libexec/gnubin:\
        $HOME/bin:\
        /usr/local/bin:\
        /usr/local/opt:\
        $HOME/.poetry/bin:\
        $HOME/Library/Python/3.8/bin:\
        /usr/local/lib/node_modules/bin:\
        /usr/local/texlive/2020/texmf-dist/doc/info:\
        /usr/local/Cellar/ruby/2.7.1_2/bin:\
        /usr/local/opt/cython/bin:\
        /bin:\
        /usr/local:\
        /usr/local/sbin:\
        /usr/bin:\
        /usr/sbin:\
        /sbin:\
        /usr/libexec:\
        /usr/local/opt/sphinx-doc/bin:\
        $HOME/.dotfiles:\
        $HOME/.dotfiles/git-achievements:"
        # '$PWD'

    PATH="${PATH// /}" # remove spaces

    # vscode is kinda odd sometimes ... someitmes with spaces, sometimes not ???
    #   so ... I'm putting the 'space remover' before it ...
    # PATH="$PATH:/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/bin:"
    PATH=$PATH'/Applications/Visual Studio Code.app/Contents/Resources/app/bin:'

    PATH="${PATH/::/:/}" # remove double colons ... you know you've done it, too

    export PATH
