#!/usr/bin/env zsh
# -*- coding: utf-8 -*-
    # shellcheck shell=bash
    # shellcheck source=/dev/null
    # shellcheck disable=2128

SET_DEBUG=${SET_DEBUG:-0} # set to 1 for verbose testing

# ?########################################## parameter expansion tips
    #? ${PATH//:/\\n}    - replace all colons with newlines
    #? ${PATH// /}       - strip all spaces
    #? ${VAR##*/}        - return only final element in path (program name)
    #? ${VAR%/*}         - return only path (without program name)

# ?########################################## PIPLIST
    # PIPLIST is not part of the normal python installation. It returns a list
    # of names of installed packages suitable for process and piping, without
    # the header and extra fields. The function recreates the list on demand
    # so it is always current.
    PIPLIST() { pip3 list | sed 's/  */ /g' | cut -d ' ' -f 1 | tail -n +3; }

# ?########################################## MANPATH
    declare -x MANPATH=" \
        /usr/local/opt/coreutils/libexec/gnuman:\
        /usr/share/man:\
        /usr/local/share/man:\
        /usr/local/opt/erlang/lib/erlang/man:\
        /Library/Frameworks/Python.framework/Versions/3.8/share/man/man1:\
        "
    MANPATH="${MANPATH// /}"

# ?########################################## PATH
    # These are automatically added to the start:
    #   /Users/skeptycal/.cabal/bin
    #   /Users/skeptycal/.ghcup/bin

# /Library/Frameworks/Python.framework/Versions/3.8/bin:\
# $HOME/Library/Python/3.8/bin:\
# /usr/local/opt/llvm/bin:\
# $HOME/Documents/coding/python/autosys/autosys:\
# $HOME/Documents/coding/python/autosys/bin:\

PATH="${PATH}"
declare -x PATH="\
/usr/local/Cellar/python@3.8/3.8.3/bin:\
/usr/local/opt/coreutils/libexec/gnubin:\
/usr/local/bin:\
/usr/local/lib/node_modules:\
/usr/local/opt/cython/bin:\
$HOME/bin:\
/bin:\
/usr/local/opt:\
/usr/local:\
/usr/local/sbin:\
/usr/bin:\
/usr/sbin:\
/sbin:\
/usr/libexec:\
$HOME/.dotfiles:\
$HOME/.dotfiles/git-achievements:\
/Applications/Visual Studio Code.app/Contents/Resources/app/bin
$PWD:\
"

PATH="${PATH// /}"
PATH="${PATH//::/:}"
# PATH="$PATH:/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin:"
export PATH

# ?########################################## OpenSSL info
    # openssl is keg-only, which means it was not symlinked into /usr/local,
    # because Apple has deprecated use of OpenSSL in favor of its own TLS and
    # crypto libraries.
    # export PATH="/usr/local/opt/openssl/bin:$PATH"

    # A CA file has been bootstrapped using certificates from the SystemRoots
    # keychain. To add additional certificates (e.g. the certificates added in
    # the System keychain), place .pem files in
    #   /usr/local/etc/openssl/certs
    #
    # and run
    #   /usr/local/opt/openssl/bin/c_rehash

# ?########################################## Notes
    # This is what was there before I added mine (6/27/19)
    # /usr/local/bin
    # /usr/bin
    # /bin
    # /usr/sbin
    # /sbin
    # /Library/TeX/texbin
    # /usr/local/share/dotnet
    # /opt/X11/bin
    # ~/.dotnet/tools
    # /Library/Frameworks/Mono.framework/Versions/Current/Commands
    # /Applications/Postgres.app/Contents/Versions/latest/bin
    # /Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin
    # $HOME/perl5/bin

    #   ! This should be either first or last ... it is up for debate
    #   I put mine first and curate what I place in here ...
    #   I put my ~/.dotfiles directory at the end of the path ... it is handy

    #   I put my /usr/libexec directory at the end ... sometimes handy
    #        * $HOME/bin:\ (and several utilities directories)

    #   Path entries that should be before all others, if possible:
    #
    #     1. gnubin - GNU replacements for macOS shell functions
    #        * /usr/local/opt/coreutils/libexec/gnubin:\

    #   Path entries that should be first - ish (before system paths):
    #     2. Programming languages
    #        * .dotnet
    #        * Python / pip / pipenv / virtualenv
    #        * anaconda / conda
    #        * PHP (path to brew version! *probably* /usr/local/bin/php)
    #        * Ruby / gems
    #        * Go
    #        * other languages or priority (non-Apple) applications
    #        * /usr/local/bin ... this seems to be the devault Brew
    #        *    symlink home and *should* catch everything else
    #        * especially programs that update an apple functionality!

    #     3. PHP tools: If you use composer, phpunit, php_codesniffer, etc
    #        * $HOME/.composer/vendor/bin:\
    #        * $HOME/.composer/vendor/squizlabs/php_codesniffer/bin:\
    #     3a.
    #        * httpd seems to have issues with Mojave
    #        * use path to brew version: /usr/local/bin/httpd and 'Brew Services Start httpd'
    #    Path entries that should be after specific app paths
    #     4. System bin paths (Homebrew compatible - 'local' first)
    #        * /usr/local/bin:\
    #        * /usr/bin:\
    #        * /bin:\

    #     5. opt's and lib's (only if needed - I symlink to 'bins' instead)
    #        * /usr/local/opt:/opt/local/sbin:\
    #        * /usr/local:\

    #     6. System sbin paths
    #        * /usr/local/sbin:\
    #        * /usr/sbin:\
    ##########################################################################
