#!/usr/bin/env zsh
# -*- coding: utf-8 -*-
	# shellcheck shell=bash
	# shellcheck source=/dev/null
	# shellcheck disable=2178,2139

 #? ######################## Main Alias file

source_dir "${DOTFILES_INC}/alias_fol"

 #? ######################## End of
