#!/usr/bin/env zsh
# -*- coding: utf-8 -*-
    # shellcheck shell=bash
    # shellcheck source=/dev/null
    # shellcheck disable=2178,2128,2206,2034
#? -----------------------------> gomake.sh - tools for repo management for macOS with zsh
	#*	system functions
	#*  tested on macOS Big Sur and zsh 5.8
	#*	copyright (c) 2021 Michael Treanor
	#*	MIT License - https://www.github.com/skeptycal
#? -----------------------------> https://www.github.com/skeptycal
#? -----------------------------> parameter expansion tips
 #? ${PATH//:/\\n}    - replace all colons with newlines
 #? ${PATH// /}       - strip all spaces
 #? ${VAR##*/}        - return only final element in path (program name)
 #? ${VAR%/*}         - return only path (without program name)

#? -----------------------------> environment
    DOTFILES_INC=~/.dotfiles/zshrc_inc # TODO - this is getting lost somewhere in the mix

	# repo_tools.sh includes ansi_colors.sh
	. ${DOTFILES_INC}/gomake_main.sh || . $(which gomake_main.sh)

	declare -ix SET_DEBUG=${SET_DEBUG:-0}  		#! set to 1 for verbose testing
    dbinfo "\${DOTFILES_INC}: ${DOTFILES_INC}"

    SCRIPT_NAME=${0##*/}
    dbinfo "\${SCRIPT_NAME}: ${SCRIPT_NAME}"

#? -----------------------------> debug info
	_debug_tests() {
		if (( SET_DEBUG )); then
			printf '%b\n' "${WARN:-}Debug Mode Details for ${CANARY}${SCRIPT_NAME##*/}${RESET:-}"
			# green "Today is $today"
			_test_args "$@"
			# dbecho "DEBUG mode is enabled. Set it to 0 to disable these messages."
		fi
		}
    _debug_tests "$@"

#!------------------------> main

    export default_repo_version='v0.1.0'
    version=$(_get_version)
    make_private='public'
    _gomake_usage_string="[init [private]|files|devtag|bump|help|version]"
    _setup_variables
SET_DEBUG=0
	dbecho "run gomake_menu ..."
    gomake_menu "$@"
