#####################################################################
#     pc.sh : pre-commit automation for macOS version 0.5.0

#     copyright 2019 (c) Michael Treanor <https://www.github.com/skeptycal>
#     MIT License <https://opensource.org/licenses/MIT>

#     Usage: ./pc.sh {init|version|help}

# Only run if changes to the yaml configuration are needed.

# Please make changes directly to the "template" file:
#     .pre-commit-template.yaml
# and run the script "./pc.sh" from this directory to update this file.

# Please do not make changes directly to the "config" file. The "config" file:
#     .pre-commit-config.yaml
# is created and updated by the pc.sh script found in the same directory
# in order to maintain the correct, current versioning from git (master sha)

default_language_version:
    python: python3.7
exclude: "^$"
fail_fast: false
repos:
    - repo: git://github.com/pre-commit/pre-commit-hooks
      sha: master
      hooks:
          - id: check-added-large-files
          - id: check-byte-order-marker
          - id: check-docstring-first
          - id: check-case-conflict
          - id: check-json
          - id: check-merge-conflict
          - id: check-symlinks
          # -   id: check-yaml
          #    -   id: detect-aws-credentials
          - id: detect-private-key
          - id: end-of-file-fixer
          - id: flake8
          # -   id: pretty-format-json
          - id: requirements-txt-fixer
          - id: trailing-whitespace
# -   repo: git://github.com/pre-commit/mirrors-pylint
#     sha: master
#     hooks:
#     -   id: pylint
