language: python
cache:
  directories:
    - "$HOME/.cache/pip"
    - "$HOME/.pyenv"
matrix:
  include:
    - python: 2.6
      dist: trusty
    - python: 2.7
    - python: 3.3
      dist: trusty
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.8
    - python: pypy
    - python: pypy3
    - python: 3.8
      services:
        - docker
      env: BUILD_SDIST=true
    - name: Python 2.7.12 on macOS
      os: osx
      osx_image: xcode9.4
      language: objective-c
      env: PYENV_VERSION=2.7.12
    - name: Python 3.6.5 on macOS
      os: osx
      osx_image: xcode10.2
      language: objective-c
      env: PYENV_VERSION=3.6.5
    - name: Python 3.7.4 on macOS
      os: osx
      osx_image: xcode11.2
      language: objective-c
      env: PYENV_VERSION=3.7.4
virtualenv:
  system_site_packages: true
install:
  - pip install -e . --use-mirrors
before_script:
  - pip install -r test_requirements.txt --use-mirrors
  - pip install .
  # - git clone https://github.com/z4r/python-coveralls-example.git
  # - cd python-coveralls-example
  # - git checkout -qf 17b8119796516195527dcb4f454a2ebd41d60244
  # - py.test example/tests.py --cov=example
  # - cd -
script:
  - pytest coveralls/tests.py --doctest-modules --pep8 coveralls -v --cov coveralls --cov-report term-missing
after_success:
  - coveralls
# example from https://github.com/simplejson/simplejson/blob/master/.travis.yml
# deploy:
#   provider: releases
#   file:
#     - dist/*.whl
#     - dist/*.tar.gz
#   file_glob: true
#   on:
#     repo: simplejson/simplejson
#     tags: true
#   skip_cleanup: true
#   api_key:
#     secure: FhcBCuL/33fsotaDLv157pQ0HpxYAXI9h4TNhT0CDgrh1i2J1m/hmJMqlrrn0j/E2TpYyXf1citLra6QrBP//FnFMGQ43el369tC3W9RPXYpfThzU6JcJecoWGQMMMiJgPLpOC7+tyDpphsNFKmySG/ITvX+OEZ4lzL8+1CWyRk=
