sudo rm -rf /Library/Preferences/com.apple.mail.plist
sudo rm -rf /Library/Preferences/.GlobalPreferences.plist
sudo rm -rf /Library/Preferences/com.apple.updatesettings.plist
sudo rm -rf /Library/Preferences/com.apple.security.plist
sudo rm -rf /Library/Preferences/com.apple.AssetCache.plist
sudo rm -rf /Library/Preferences/com.apple.windowserver.plist
sudo rm -rf /Library/Preferences/com.apple.PowerManagement.plist
sudo rm -rf /Library/Preferences/com.apple.locationmenu.plist
sudo rm -rf /Library/Preferences/com.apple.alf.plist
sudo rm -rf /Library/Preferences/com.apple.PowerManagement.E3B4B9FD-2153-590F-9E64-DF142924595C.plist
sudo rm -rf /Library/Preferences/com.apple.TimeMachine.plist
sudo rm -rf /Library/Preferences/com.apple.noticeboard.plist
sudo rm -rf /Library/Preferences/com.apple.SoftwareUpdate.plist
sudo rm -rf /Library/Preferences/com.apple.networkextension.necp.plist
sudo rm -rf /Library/Preferences/com.apple.MCX.plist
sudo rm -rf /Library/Preferences/com.apple.loginwindow.plist
sudo rm -rf /Library/Preferences/com.apple.FindMyMac.plist
sudo rm -rf /Library/Preferences/com.apple.powerlogd.plist
sudo rm -rf /Library/Preferences/com.apple.networkextension.uuidcache.plist
sudo rm -rf /Library/Preferences/com.apple.apsd.plist
