#!/usr/bin/env zsh
# -*- coding: utf-8 -*-
# shellcheck shell=bash
# shellcheck source=/dev/null
# shellcheck disable=SC1090,SC2128,SC2178


# SET_DEBUG: set to 1 for verbose testing; set option -r for readonly (override future changes)
declare -ix SET_DEBUG && SET_DEBUG=0

#? ####################### initialization
# to ease the transition to zsh ...
BASH_SOURCE=${BASH_SOURCE:-$0}
# create 'realpath' function if none exists
command -v realpath >/dev/null 2>&1 || (
    realpath() {
        if [[ $1 = /* ]]; then
            echo "$1"
        else # echo "$PWD/${1#./}"
            cd -P -- "$1" || return
            pwd -P
        fi
        }
        )

declare -x SHELL_BIN="${SHELL##*/}"
declare -x SCRIPT_NAME="${BASH_SOURCE##*/}"
declare -x SCRIPT_PATH="${BASH_SOURCE%/*}"
# echo -e "$SHELL_BIN"
# echo -e "$BASH_SOURCE"
# echo -e "$SCRIPT_NAME"
# echo -e "$SCRIPT_PATH"

#? ######################## ssm modules
. "$(command -v ssm_constants)"
# . "$(command -v ssm_init)"
. "$(command -v ssm_debug)"
. "$(command -v ssm_usage)"


_run_tests() {
    for var in $(export -a | cut -d '=' -f 1); do
        # which_var $var
        attn "\$var: $var"
        attn "$(eval "value=\"\${$var}\"")"
        # shellcheck disable=SC2016
        attn '  \$${var}: '"$(eval echo -e \$${var})"
        if [[ $SHELL_BIN == 'zsh' ]]; then
            attn "  \${\!var}: ${(p)var}"
        else
            attn "  \${!var}: ${!var}"
        fi
    done
    }

#? ######################## main loop
_main_loop() {
    #? ######################## project information
    declare -x NAME && NAME=${NAME:-"${BASH_SOURCE##*/}"}
    # echo "NAME: $NAME"
    declare -x VERSION && VERSION=${VERSION:-'1.4.0'}
    declare -x DESC && DESC=${DESC:-'Script Resources for ssm on macOS'}
    declare -x USAGE && USAGE="${NAME:-'ssm'} [help|test|usage|version]"

    set_man_page
    # [[ $SET_DEBUG == 1 ]] && _run_tests "$@"
    }

#! ######################## entry point
# [[ $SSM_LOADED == 1 ]] || _main_loop "$@"
_main_loop "$@"
declare -ix SSM_LOADED && SSM_LOADED=1       # prevent repeat loading
