#!/usr/bin/env zsh
# -*- coding: utf-8 -*-
. ssm_init

#? ######################## Project Information
    declare -x NAME=${NAME:="${BASH_SOURCE##*/}"}
    declare -x VERSION=${VERSION:='1.4.0'}
    declare -x DESC=${DESC:='Script Resources for ssm on macOS'}
    declare -x USAGE="source ${NAME:-} [help|test|usage|version]"

#! ######################## main loop
_main_loop() {
    [[ $ZSH_EVAL_CONTEXT =~ :file$ ]] || die(64)
    script_name=$NAME
    set_man_page

    parse_options "$@"
    # [[ $SET_DEBUG == 1 ]] && _run_tests "$@"
    }


usage_long_desc="$(
    cat <<usage_long_desc
    ${MAIN:-}$NAME${WHITE:-} sets and exports standard script modules containing
    constants and functions for macOS
    Tested on macOS Catalina with ${COOL:-}Python ${CANARY:-}3.8${WHITE:-} ... includes ANSI color constants:

    Includes a few basic ANSI color constants:

    ${MAIN:-}MAIN   ${WARN:-}WARN   ${COOL:-}COOL   ${LIME:-}LIME   ${GO:-}GO   ${CHERRY:-}CHERRY   ${CANARY:-}CANARY   ${ATTN:-}ATTN   ${RAIN:-}RAIN   ${RESET:-}RESET
usage_long_desc
)"
usage_parameters="$(
    cat <<usage_parameters
    help      - display complete usage information (this!)
    test      - perform script tests
    usage     - display short usage instructions
    version   - display version information
usage_parameters
)"

#* ######################## entry point
_main_loop "$@"
set +avx
#? ############################################################################
#* Resources found in ssm_resources
    # _debug_function_header, in_list
    #* ######################## C++ style error messages
    # EX_OK, EX_USAGE, EX_DATAERR, EX_NOINPUT, EX_NOUSER, EX_NOHOST, EX_UNAVAILABL, EX_SOFTWARE, EX_OSERR, EX_OSFILE, EX_CANTCREAT, EX_IOERR, EX_TEMPFAIL, EX_PROTOCOL, EX_NOPERM, EX_CONFIG
    #* ######################## BASH trap signals
    # TRAP_SIGHUP, TRAP_SIGINT, TRAP_SIGQUIT, TRAP_SIGILL, TRAP_SIGTRAP, TRAP_SIGABRT, TRAP_SIGEMT, TRAP_SIGFPE, TRAP_SIGKILL, TRAP_SIGBUS, TRAP_SIGSEGV, TRAP_SIGSYS, TRAP_SIGPIPE, TRAP_SIGALRM, TRAP_SIGTERM, TRAP_SIGURG, TRAP_SIGSTOP, TRAP_SIGTSTP, TRAP_SIGCONT, TRAP_SIGCHLD, TRAP_SIGTTIN, TRAP_SIGTTOU, TRAP_SIGIO, TRAP_SIGXCPU, TRAP_SIGXFSZ, TRAP_SIGVTALRM, TRAP_SIGPROF, TRAP_SIGWINCH, TRAP_SIGINFO, TRAP_SIGUSR1, TRAP_SIGUSR2
    #* ######################## ANSI constants for common colors
    # br, ce, me, warn, blue, green, cherry, canary, attn, purple, rain, white
    # MAIN, WARN, COOL, BLUE, GO, CHERRY, CANARY, ATTN, PURPLE, RAIN, WHITE, RESTORE, RESET_FG
    #* ######################## program configuration
    # set_man_page, get_linux_platform_name, get_current_os_name
    #* ######################## program control flow functions
    # async_run, db_echo, die, yes_no, no_yes, exit_usage, print_usage, db_script_source
    #* ######################## file manipulation functions
    # source_file, hex_dump, url_encode, url_decode
    #* ######################## path manipulation functions
    # real_name, parse_filename, get_safe_new_filename
