#!/usr/bin/env zsh
# -*- coding: utf-8 -*-
declare -ix SET_DEBUG=${SET_DEBUG:=0}   # set to 1 for verbose testing
#? ######################## initialization

# create 'realpath' function if none exists
command -v realpath >/dev/null 2>&1 || realpath() { [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}" }

# is script 'scourced?'
[[ $ZSH_EVAL_CONTEXT =~ :file$ ]] && is_sourced=1 || is_sourced=0

_run_tests() {
    blue "$0 - \$BASH_SOURCE $BASH_SOURCE"
    which_var "$SET_DEBUG"
    which_var "$SSM_LOADED"
    which_var "$SCRIPT_SOURCE"
    which_var "$BASE_DIR"
}

#! ######################## main loop
_main_loop() {
        [[ $SET_DEBUG == 1 ]] && _run_tests "$@"
    }

#! ######################## entry point
_main_loop "$@"
