#!/usr/bin/env false zsh
# -*- coding: utf-8 -*-

#? ######################## global constants
    NAME="ssm"
    VERSION='1.4.0'
    DESC='personalized Bash / Zsh functions (macOS)'
    AUTHOR="Michael Treanor  <skeptycal@gmail.com>"
    COPYRIGHT="Copyright (c) 2019 Michael Treanor"
    LICENSE="MIT <https://opensource.org/licenses/MIT>"
    GITHUB="https://www.github.com/skeptycal"
    USAGE() { echo -e "${NAME:-'Skeptycal Software'} [help|test|usage|version]"; }


# TODO perhaps include these? output of kill -l
    # HUP INT QUIT ILL TRAP ABRT EMT FPE KILL BUS SEGV
    # SYS PIPE ALRM TERM URG STOP TSTP CONT CHLD TTIN
    # TTOU IO XCPU XFSZ VTALRM PROF WINCH INFO USR1 USR2
#? ######################## path constants
    declare -x TEMP_DIR="$(mktemp -q -d -t "$(basename "$0").XXXXXX" 2>/dev/null || mktemp -q -d)"
    declare -x TEMP_FILE="$TEMP_DIR/tmp_proc_random.$$.$RANDOM"
    declare -x SYS_USERID="$(id -un):$(id -gn)"
    declare -x SRC_PATH="${SCRIPT_PATH}/src"
    declare -x BAK_PATH="${SCRIPT_PATH}/bak"
    declare -x BIN_PATH="${HOME}/bin/utilities/pc_bak"
    declare -x DOTFILES_PATH="${HOME}/.dotfiles"
    declare -x HERE="$PWD"
    declare -x NEWLINE='
'

#? ######################## program constants
    declare -x _pretty_usage="Usage :\n\t${MAIN}pretty${WHITE} [file(s) ...] \t\t- use list of files (default is all files in current directory)\n\t${MAIN}pretty${WHITE} [-m [commit message]] \t- use git staged files and commit with message
        \n\t${MAIN}pretty${WHITE} [-h|--help|help] \t- usage help (this!)"

    declare -x _debug_function_header_text='_header_test_log "Calling: ${CANARY:-}${FUNCNAME[0]} ${MAIN:-}$*${RESET:-}"'

#? ######################## setup C++ style error messages
    # reference: Advanced Bash-Scripting Guide
    #   <http://tldp.org/LDP/abs/html/exitcodes.html#EXITCODESREF>

    # from /usr/include/sysexits.h
    # Copyright (c) 1987, 1993
    # The Regents of the University of California.  All rights reserved.
    declare -ix EX_OK=0                  # successful termination

    # The Linux Documentation Project has a list of reserved codes that also offers advice on what code to use for specific scenarios. These are the standard error codes in Linux or UNIX.
    declare -ix EX_ERROR=1               # catchall for general errors
    declare -ix EX_SHELLERR=2            # misuse of shell builtins (BASH); missing keyword

    declare -ix EX__BASE=64              # base value for error messages
    declare -ix EX_USAGE=64              # command line usage error
    declare -ix EX_DATAERR=65            # data format error
    declare -ix EX_NOINPUT=66            # cannot open input
    declare -ix EX_NOUSER=67             # addressee unknown
    declare -ix EX_NOHOST=68             # host name unknown
    declare -ix EX_UNAVAILABL=69         # service unavailable
    declare -ix EX_SOFTWARE=70           # internal software error
    declare -ix EX_OSERR=71              # system error (e.g., can't fork)
    declare -ix EX_OSFILE=72             # critical OS file missing
    declare -ix EX_CANTCREAT=73          # can't create (user) output file
    declare -ix EX_IOERR=74              # input/output error
    declare -ix EX_TEMPFAIL=75           # temp failure; user is invited to retry
    declare -ix EX_PROTOCOL=76           # remote error in protocol
    declare -ix EX_NOPERM=77             # permission denied
    declare -ix EX_CONFIG=78             # configuration error
    declare -ix EX__MAX=78               # maximum listed value

    # Linux / Unix codes
    declare -ix EX_CANTEXECUTE=126       # command invoked cannot execute
    declare -ix EX_NOTFOUND=127          # command not found; possible $PATH error or typo
    declare -ix EX_BADARG=128            # invalid argument
    declare -ix EX_FATALARG=129          # fatal error
    declare -ix EX_CTRL_C=130            # script terminated by Control-C

#? ######################## setup trap signal messages
    # https://linuxconfig.org/how-to-modify-scripts-behavior-on-signals-using-bash-traps
    declare -ix TRAP_SIGHUP=1
    declare -ix TRAP_SIGINT=1
    declare -ix TRAP_SIGQUIT=1
    declare -ix TRAP_SIGILL=1
    declare -ix TRAP_SIGTRAP=1
    declare -ix TRAP_SIGABRT=1
    declare -ix TRAP_SIGEMT=1
    declare -ix TRAP_SIGFPE=1
    declare -ix TRAP_SIGKILL=1
    declare -ix TRAP_SIGBUS=1
    declare -ix TRAP_SIGSEGV=1
    declare -ix TRAP_SIGSYS=1
    declare -ix TRAP_SIGPIPE=1
    declare -ix TRAP_SIGALRM=1
    declare -ix TRAP_SIGTERM=1
    declare -ix TRAP_SIGURG=1
    declare -ix TRAP_SIGSTOP=1
    declare -ix TRAP_SIGTSTP=1
    declare -ix TRAP_SIGCONT=1
    declare -ix TRAP_SIGCHLD=1
    declare -ix TRAP_SIGTTIN=1
    declare -ix TRAP_SIGTTOU=1
    declare -ix TRAP_SIGIO=1
    declare -ix TRAP_SIGXCPU=1
    declare -ix TRAP_SIGXFSZ=1
    declare -ix TRAP_SIGVTALRM=1
    declare -ix TRAP_SIGPROF=1
    declare -ix TRAP_SIGWINCH=1
    declare -ix TRAP_SIGINFO=1
    declare -ix TRAP_SIGUSR1=1
    declare -ix TRAP_SIGUSR2=1

#? ######################## setup ANSI constants for common colors
    declare -x MAIN=$(echo -en '\001\033[38;5;229m')
    declare -x WARN=$(echo -en '\001\033[38;5;203m')
    declare -x COOL=$(echo -en '\001\033[38;5;38m')
    declare -x BLUE=$(echo -en '\001\033[38;5;38m')
    declare -x GO=$(echo -en '\001\033[38;5;28m')
    declare -x LIME=$(echo -en '\001\033[32;1m')
    declare -x CHERRY=$(echo -en '\001\033[38;5;124m')
    declare -x CANARY=$(echo -en '\001\033[38;5;226m')
    declare -x ATTN=$(echo -en '\001\033[38;5;178m')
    declare -x PURPLE=$(echo -en '\001\033[38;5;93m')
    declare -x RAIN=$(echo -en '\001\033[38;5;93m')
    declare -x WHITE=$(echo -en '\001\033[37m')
    declare -x RESTORE=$(echo -en '\001\033[0m\002')
    declare -x RESET=$(echo -en '\001\033[0m')
    declare -x RESET_FG=$RESET

#? ######################## setup functions for printing lines in common colors
    br() { printf "\n"; } # yes, this is a fake cli version of <br />
    ce() { printf "%b\n" "${@:-}${RESET:-}"; }
    me() { ce "${MAIN:-}${@:-}"; }
    warn() { ce "${WARN:-}${@:-}"; }
    blue() { ce "${COOL:-}${@:-}"; }
    cool() { ce "${COOL:-}${@:-}"; }
    green() { ce "${GO:-}${@:-}"; }
    lime() { ce "${LIME:-}${@:-}"; }
    cherry() { ce "${CHERRY:-}${@:-}"; }
    canary() { ce "${CANARY:-}${@:-}"; }
    attn() { ce "${ATTN:-}${@:-}"; }
    purple() { ce "${PURPLE:-}${@:-}"; }
    rain() { ce "${RAIN:-}${@:-}"; }
    white() { ce "${WHITE:-}${@:-}"; }

#? ######################## setup default package description and usage
declare -x usage_long_desc="$(
    cat <<usage_long_desc
    ${MAIN:-}$NAME${WHITE:-} sets and exports standard script modules containing
    constants and functions for macOS
    Tested on ${LIME:-}macOS Catalina${WHITE:-} with ${COOL:-}Python ${CANARY:-}3.8${WHITE:-} ... includes ANSI color constants:

    Includes a few basic ANSI color constants:

    ${MAIN:-}MAIN   ${WARN:-}WARN   ${COOL:-}COOL   ${LIME:-}LIME   ${GO:-}GO   ${CHERRY:-}CHERRY   ${CANARY:-}CANARY   ${ATTN:-}ATTN   ${RAIN:-}RAIN   ${RESET:-}RESET
usage_long_desc
)"
declare -x usage_parameters="$(
    cat <<usage_parameters
    help      - display complete usage information (this!)
    test      - perform script tests
    usage     - display short usage instructions
    version   - display version information
usage_parameters
)"

# ######################## ssm_constants contents:
    #? ######################## C++ style error messages
    # EX_OK, EX_USAGE, EX_DATAERR, EX_NOINPUT, EX_NOUSER, EX_NOHOST, EX_UNAVAILABL, EX_SOFTWARE, EX_OSERR, EX_OSFILE, EX_CANTCREAT, EX_IOERR, EX_TEMPFAIL, EX_PROTOCOL, EX_NOPERM, EX_CONFIG
    #? ######################## BASH trap signals
    # TRAP_SIGHUP, TRAP_SIGINT, TRAP_SIGQUIT, TRAP_SIGILL, TRAP_SIGTRAP, TRAP_SIGABRT, TRAP_SIGEMT, TRAP_SIGFPE, TRAP_SIGKILL, TRAP_SIGBUS, TRAP_SIGSEGV, TRAP_SIGSYS, TRAP_SIGPIPE, TRAP_SIGALRM, TRAP_SIGTERM, TRAP_SIGURG, TRAP_SIGSTOP, TRAP_SIGTSTP, TRAP_SIGCONT, TRAP_SIGCHLD, TRAP_SIGTTIN, TRAP_SIGTTOU, TRAP_SIGIO, TRAP_SIGXCPU, TRAP_SIGXFSZ, TRAP_SIGVTALRM, TRAP_SIGPROF, TRAP_SIGWINCH, TRAP_SIGINFO, TRAP_SIGUSR1, TRAP_SIGUSR2
    #? ######################## ANSI constants for common colors
    # br, ce, me, warn, blue, green, cherry, canary, attn, purple, rain, white
    # MAIN, WARN, COOL, BLUE, GO, CHERRY, CANARY, ATTN, PURPLE, RAIN, WHITE, RESTORE, RESET_FG
