#!/usr/bin/env zsh
# -*- coding: utf-8 -*-
# shellcheck shell=bash
# shellcheck source=/dev/null
# shellcheck disable=SC1090

declare -ix SET_DEBUG=${SET_DEBUG:-0}   # set to 1 for verbose testing

#?######################## SCRIPT TESTS
    _run_tests() {
        # shellcheck disable=SC2128
        blue "$0 - \$BASH_SOURCE $BASH_SOURCE"
        which_var "$SET_DEBUG"
        which_var "$SSM_LOADED"
        which_var "$SCRIPT_SOURCE"
        which_var "$BASE_DIR"
        }
#? ######################## main loop
_main_loop() {
    true
    # [[ $SET_DEBUG == 1 ]] && _run_tests "$@"
    }

#! ######################## entry point
_main_loop "$@"
