#!/usr/bin/env zsh
# -*- coding: utf-8 -*-
    # shellcheck shell=bash
    # shellcheck source=/dev/null
    # shellcheck disable=2178,2128,2206,2034
#? ################# .functions - functions for macOS with zsh ###############
	#* copyright (c) 2019 Michael Treanor     -----     MIT License
	#* should not be run directly; called from .bash_profile / .bashrc / .zshrc
#? ######################## https://www.github.com/skeptycal #################
	# SET_DEBUG=${SET_DEBUG:-0} # set to 1 for verbose testing
	# SCRIPT_NAME=${0##*/}
	# set -a
# 	_debug_tests() {
# 		if (( SET_DEBUG == 1 )); then
# 			printf '%b\n' "${WARN:-}Debug Mode Details for ${CANARY}${SCRIPT_NAME##*/}${RESET:-}"
# 			color_sample
# 		fi
# 	}
# #? ###################### copyright (c) 2019 Michael Treanor #################


#? ######################## Terminal


	# # terminal identification
    # if [[ $COLORTERM = gnome-* && $TERM = xterm ]] && infocmp gnome-256color >/dev/null 2>&1; then
    #     declare -x TERM='gnome-256color';
    # elif infocmp xterm-256color >/dev/null 2>&1; then
    #     declare -x TERM='xterm-256color';
    # fi;

	# # Highlight the user name when logged in as root.
    # if [[ "${USER}" == "root" ]]; then
    #     declare -x userStyle="\${red}"
    # else
    #     declare -x userStyle="\${orange}"
    # fi

#? ######################## Terminal Colors
	# # GIT colors
    # declare -x WS="$(git config --get-color color.diff.whitespace "blue reverse")"
    # declare -x RESET="$(git config --get-color "" "reset")"

    # Archived

    # RED=$WARN
    # setup_color() {
    #     # Only use colors if connected to a terminal
    #     if [ -t 1 ]; then
    #         declare -g RED=$(printf '\033[31m')
    #         declare -g GREEN=$(printf '\033[32m')
    #         declare -g YELLOW=$(printf '\033[33m')
    #         declare -g BLUE=$(printf '\033[34m')
    #         declare -g BOLD=$(printf '\033[1m')
    #         declare -g RESET=$(printf '\033[m')
    #     else
    #         declare -g RED=""
    #         declare -g GREEN=""
    #         declare -g YELLOW=""
    #         declare -g BLUE=""
    #         declare -g BOLD=""
    #         declare -g RESET=""
    #     fi
    #     }

    # setup_color
